name: Clang format
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '2'
      
    - name: Install Dependencies
      run: | 
        sudo apt install clang-format-10
        clang-format-10 --version

    - name: Clang format
      run: |
        git clang-format-10 HEAD~1
        git diff --exit-code