name: Coverage CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx: ["g++-10"]
        include: 
          - cxx: "g++-10"
            cc: "gcc-10"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' 
    - uses: BSFishy/pip-action@v1
      with:
        packages: conan

    - name: Cache Conan
      id: cache-conan
      uses: actions/cache@v2
      with:
        path: ~/.conan
        key:
          conan-cache-${{ runner.os }}-${{ matrix.cxx }}
        restore-keys: |
          conan-cache-${{ runner.os }}-${{ matrix.cxx }}
      
    - name: Install Dependencies
      run: sudo apt install cmake g++-10
        
    - name: Print System Information
      run: |
        cmake --version
        ${{ matrix.cxx }} --version

    - name: Install Conan Dependencies
      env: 
        CXX: ${{ matrix.cxx }}
        CC: ${{ matrix.cc}}
      run: |
        echo $CXX
        echo $CC
        mkdir build && cd build
        conan install .. -s compiler.libcxx=libstdc++11 --build missing
        

    - name: Install Hsm
      env: 
        CXX: ${{ matrix.cxx }}
        CC: ${{ matrix.cc}}
      run: |
        echo $CXX
        echo $CC
        cd build && mkdir install
        cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DHSM_GCC_COVERAGE=ON
        cmake --build . --target install
        
    - name: Run Hsm Tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cd build 
        ctest -VV
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'