name: Coverage CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      CC: gcc-10
      CXX: g++-10

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: BSFishy/pip-action@v1
      with:
        packages: conan

    - name: Cache Conan
      uses: actions/cache@v2
      with:
        path: ~/.conan
        key: conan-cache-${{ hashFiles('**/conanfile.txt') }}-g++-10

    - name: Install Conan Dependencies
      run: |
        for dir in . test; do
          conan install $dir -if deps \
          -s compiler.libcxx=libstdc++11 \
          --build missing
        done

    - name: Configure Hsm
      run: cmake -S test -B build -D CMAKE_BUILD_TYPE=Release
        -D HSM_GCC_COVERAGE=ON
        -D "CMAKE_PREFIX_PATH=${PWD}/deps"

    - name: Build Hsm
      run: cmake --build build -j 2

    - name: Install Hsm
      run: cmake --install build --prefix install

    - name: Run Hsm Tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cd build
        ctest --output-on-failure
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
