name: Coverage CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      CC: gcc-10
      CXX: g++-10

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: BSFishy/pip-action@v1
      with:
        packages: conan

    - name: Cache Conan
      uses: actions/cache@v2
      with:
        path: ~/.conan
        key: conan-cache-${{ hashFiles('conanfile.txt') }}-g++-10

    - name: Install Conan Dependencies
      run: |
        set -e
        mkdir -p build/dependencies/conan
        cd build/dependencies/conan
        conan install ../../.. -s compiler.libcxx=libstdc++11 --build missing

    - name: Cache GTest
      uses: actions/cache@v2
      with:
        path: build/dependencies/gtest
        key: gtest-cache-${{ hashFiles('script/install_gtest.sh') }}-g++-10

    - name: Install GoogleTest
      run: script/install_gtest.sh

    - name: Configure Hsm
      run: cmake -S test -B build/test -D CMAKE_BUILD_TYPE=Release
        -D HSM_GCC_COVERAGE=ON
        -D "CMAKE_MODULE_PATH=${PWD}/build/dependencies/conan"
        -D "CMAKE_PREFIX_PATH=${PWD}/build/dependencies/gtest"

    - name: Build Hsm
      run: cmake --build build/test -j 2

    - name: Install Hsm
      run: cmake --install build/test --prefix install

    - name: Run Hsm Tests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        cd build/test
        ctest --output-on-failure
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
