name: macOS CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: BSFishy/pip-action@v1
      with:
        packages: conan

    - name: Cache Conan
      uses: actions/cache@v2
      with:
        path: ~/.conan
        key: conan-cache-${{ hashFiles('conanfile.txt') }}-macos

    - name: Install Conan Dependencies
      run: |
        set -e
        mkdir -p build/dependencies/conan
        cd build/dependencies/conan
        conan install ../../.. --build missing -o boost:without_fiber=True

    - name: Cache GTest
      uses: actions/cache@v2
      with:
        path: build/dependencies/gtest
        key: gtest-cache-${{ hashFiles('script/install_gtest.sh') }}-macos

    - name: Install GoogleTest
      run: script/install_gtest.sh

    - name: Configure Hsm
      run: cmake -S test -B build/test -D CMAKE_BUILD_TYPE=Release
        -D "CMAKE_MODULE_PATH=${PWD}/build/dependencies/conan"
        -D "CMAKE_PREFIX_PATH=${PWD}/build/dependencies/gtest"

    - name: Build Hsm
      run: cmake --build build/test -j 2

    - name: Install Hsm
      run: cmake --install build/test --prefix install

    - name: Run Hsm Tests
      working-directory: build/test
      run: ctest --output-on-failure
