name: macOS CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: BSFishy/pip-action@v1
      with:
        packages: conan

    - name: Cache Conan
      uses: actions/cache@v2
      with:
        path: ~/.conan
        key: conan-cache-${{ hashFiles('**/conanfile.txt') }}-macos

    - name: Install Conan Dependencies
      run: |
        for dir in . test; do
          conan install $dir -if deps -o boost:without_fiber=True
        done

    - name: Configure Hsm
      run: cmake -S test -B build/test -D CMAKE_BUILD_TYPE=Release
        -D "CMAKE_PREFIX_PATH=${PWD}/deps"

    - name: Build Hsm
      run: cmake --build build/test -j 2

    - name: Install Hsm
      run: cmake --install build/test --prefix install

    - name: Run Hsm Tests
      working-directory: build/test
      run: ctest --output-on-failure
