name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x' 
      - uses: BSFishy/pip-action@v1
        with:
          packages: conan
        
      - name: Conan Install
        run: conan install . --build missing

      - name: Install Hsm
        run: |
         cmake . -DCMAKE_BUILD_TYPE=DEBUG
         cmake --build . --target install

      - name: Run Hsm Tests
        run: ctest -VV -C Debug
