name: Windows CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: BSFishy/pip-action@v1
      with:
        packages: conan

    - name: Cache Conan
      uses: actions/cache@v2
      with:
        path: .conan
        key: conan-cache-${{ hashFiles('conanfile.txt') }}-windows

    - run: mkdir -p build/dependencies/conan

    - name: Install Conan Dependencies
      working-directory: build/dependencies/conan
      shell: bash
      env: { CONAN_USER_HOME: '${{ github.workspace }}/.conan' }
      run: conan install ../../.. --build missing

    - name: Configure Hsm
      run: >-
        $pwd = (Get-Location) -replace "\\", "/"

        & cmake -S test -B build/test
        -D "CMAKE_MODULE_PATH=${pwd}/build/dependencies/conan"

        if ($LASTEXITCODE -ne 0) { throw "Exit code is $LASTEXITCODE" }

    - name: Build Hsm
      run: cmake --build build/test --config Debug -j 2

    - name: Install Hsm
      run: cmake --install build/test --config Debug --prefix install

    - name: Run Hsm Tests
      working-directory: build/test
      run: ctest --output-on-failure -C Debug
